spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: '${AUTH0_CLIENT_ID:}'
            client-secret: '${AUTH0_CLIENT_SECRET:}'
            authorization-grant-type: 'authorization_code'
            redirect-uri: 'http://localhost:8080/login/oauth2/code/auth0'
            scope: ['openid', 'profile', 'email']
        provider:
          auth0:
            issuer-uri: '${AUTH0_ISSUER_URI:}'