spring:
  config:
    import: optional:secrets.yml
  security:
     oauth2:
       client:
         registration:
           google:
             client-id: ${secrets.googleClientKey}'
             client-secret: '${secrets.googleClientSecret}'
             redirect-uri: '${secrets.googleRedirectUri}'